#!/usr/bin/env python3
"""从 tokens.json 生成 tokens.css 与 api/tokens.md。

设计系统页面只在页面内保存时重新生成这两个文件；从仓库发布 tokens.json 后它们不会更新，
因此用本脚本按页面的生成格式重建，再随 tokens.json 一起发布。

用法：python3 design-system/tools/compile-tokens.py [project 目录]
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "project"

OTHER_TITLES = {"size": "Size", "zIndex": "Z index", "duration": "Duration"}


def css_value(v):
    m = re.fullmatch(r"\{([A-Za-z0-9_.-]+)\}", v)
    return f"var(--{m.group(1)})" if m else v


def per_theme(tok, themes):
    v = tok["value"]
    if isinstance(v, str):
        return {t: v for t in themes}
    first = v.get(themes[0], next(iter(v.values())))
    return {t: v.get(t, first) for t in themes}


def comment(usage):
    return f" /* {usage} */" if usage else ""


def style_props(st, group, families):
    fam = st.get("family", group.get("family"))
    return fam, st["fontSize"], st.get("lineHeight", "normal"), st.get("fontWeight", 400), st.get("letterSpacing", 0)


def compile_css(d):
    themes = [t["id"] for t in d["color"]["themes"]]
    first = themes[0]
    colorlike = d["color"]["tokens"] + d.get("shadow", {}).get("tokens", [])
    out = ["/* ENDFIELD — generated from tokens.json */", f':root, [data-theme="{first}"] {{']
    for t in colorlike:
        out.append(f"  --{t['name']}: {css_value(per_theme(t, themes)[first])};{comment(t.get('usage'))}")
    out.append("}")
    for th in themes[1:]:
        out.append(f'[data-theme="{th}"] {{')
        for t in colorlike:
            vals = per_theme(t, themes)
            if vals[th] != vals[first] or vals[th].startswith("{"):
                out.append(f"  --{t['name']}: {css_value(vals[th])};")
        out.append("}")
    out.append(":root {")
    fams = ["spacing", "radius"] + [k for k in d if k not in ("name", "version", "meta", "color", "type", "spacing", "radius", "shadow") and isinstance(d[k], dict) and "tokens" in d[k]]
    for k in fams:
        for t in d[k]["tokens"]:
            out.append(f"  --{t['name']}: {t['value']};{comment(t.get('usage'))}")
    families = d["type"]["families"]
    for key, stack in families.items():
        out.append(f"  --font-{key}: {stack};")
    for g in d["type"]["groups"]:
        for st in g["styles"]:
            fam, size, lh, w, _ = style_props(st, g, families)
            out.append(f"  --text-{st['name']}: {w} {size}/{lh} var(--font-{fam});{comment(st.get('usage'))}")
    out.append("}")
    for g in d["type"]["groups"]:
        for st in g["styles"]:
            fam, size, lh, w, ls = style_props(st, g, families)
            out += [f".{st['name']} {{", f"  font-family: var(--font-{fam});", f"  font-size: {size};",
                    f"  line-height: {lh};", f"  font-weight: {w};", f"  letter-spacing: {ls};", "}"]
    for f in d["type"]["fonts"]:
        out += ["@font-face {", f"  font-family: \"{f['family']}\";", f"  src: url(\"{f['file']}\") format(\"woff2\");",
                f"  font-weight: {f['weight']};", f"  font-style: {f.get('style', 'normal')};", "  font-display: swap;", "}"]
    return "\n".join(out) + "\n"


def ramp_key(name):
    m = re.fullmatch(r"(.+)-(\d+)", name)
    return (m.group(1), m.group(2)) if m else None


def compile_md(d):
    themes = [t["id"] for t in d["color"]["themes"]]
    first = themes[0]
    colors = d["color"]["tokens"]
    stems = {}
    for t in colors:
        k = ramp_key(t["name"])
        if k:
            stems.setdefault(k[0], []).append(t)
    ramps = {s: ts for s, ts in stems.items() if len(ts) >= 3}
    in_ramp = {t["name"] for ts in ramps.values() for t in ts}
    flat = [t for t in colors if t["name"] not in in_ramp]
    others = [k for k in d if k not in ("name", "version", "meta", "color", "type") and isinstance(d[k], dict) and "tokens" in d[k]]
    order = ["spacing", "radius", "shadow"] + [k for k in others if k not in ("spacing", "radius", "shadow")]
    title = lambda k: OTHER_TITLES.get(k, k[0].upper() + k[1:])
    summary = [f"Palette ramps and brand — {len(colors)} tokens", "Type styles, families, font files"]
    summary += [f"{title(k)} — {len(d[k]['tokens'])} tokens" for k in order if k in d]
    out = ["<!-- @generated by the Design System type on every save and build — do not edit -->", "# Tokens", "",
           "Every token of the system, a section per group: " + "; ".join(summary) + ".", "",
           "## Color · Palette ramps and brand", "", "### Use", "", "```css",
           "/* any surface that loads tokens.css or components/bundle.css */", f"color: var(--{colors[0]['name']});",
           f"/* a surface with no stylesheet (a slide): the {first} value, or another theme’s in that mode */", "```", "",
           f"### Tokens ({len(colors)})", "", "| token | " + " | ".join(themes) + " | usage |",
           "| --- | " + " | ".join("---" for _ in themes) + " | --- |"]
    byname = {t["name"]: t for t in colors}

    def resolve(v, th, depth=0):
        m = re.fullmatch(r"\{([A-Za-z0-9_.-]+)\}", v)
        return resolve(per_theme(byname[m.group(1)], themes)[th], th, depth + 1) if m and depth < 16 else v

    for t in flat:
        vals = per_theme(t, themes)
        out.append(f"| `{t['name']}` | " + " | ".join(resolve(vals[th], th) for th in themes) + f" | {t.get('usage', '')} |")
    out += ["", f"| ramp | steps | first → last ({first}) |", "| --- | --- | --- |"]
    for s, ts in ramps.items():
        out.append(f"| `{s}-*` | " + ", ".join(ramp_key(t["name"])[1] for t in ts)
                   + f" | {per_theme(ts[0], themes)[first]} → {per_theme(ts[-1], themes)[first]} |")
    ty = d["type"]
    out += ["", "## Type", "", "Use the named styles; no literal px.", "", "### Use", "", "```css",
            f"font: var(--text-{ty['groups'][0]['styles'][0]['name']});            /* with tokens.css */",
            f"font-family: var(--font-{next(iter(ty['families']))});   /* the family alone */", "```", "", "### Styles", "",
            "| style | CSS | size / line | weight | family | usage |", "| --- | --- | --- | --- | --- | --- |"]
    for g in ty["groups"]:
        for st in g["styles"]:
            fam, size, lh, w, _ = style_props(st, g, ty["families"])
            out.append(f"| `{st['name']}` | `.{st['name']}`, `--text-{st['name']}` | {size} / {lh} | {w} | `{fam}` | {st.get('usage', '')} |")
    out += ["", "### Families", "", "| family | CSS variable | stack |", "| --- | --- | --- |"]
    for k, stack in ty["families"].items():
        out.append(f"| `{k}` | `--font-{k}` | `{stack}` |")
    out += ["", "### Font files", "",
            "Fonts: one file per family is enough (below: the upright face nearest regular weight; bold and italic synthesize). Fetch it as the fetch column says (Artifact tool `read`, that id or path as `path`) and upload it as an asset where you use it (`publish`, `file_path`, `asset:true`) — HTML/CSS: an `@font-face { font-family: \"<family>\"; src: url(<uploaded>) }` rule; a Slides deck: write `fonts/<id>` = `{\"family\":\"<family>\",\"src\":\"<the url the upload returned>\"}`. `tokens.css` carries the `@font-face` rules for a page that inlines it and names each family by the CSS variable below.",
            "", "| family | file | fetch | CSS | Slides `fonts/<id>` |", "| --- | --- | --- | --- | --- |"]
    for f in ty["fonts"]:
        key = next((k for k, s in ty["families"].items() if s.split(",")[0].strip('"') == f["family"]), None)
        css = f"`var(--font-{key})`" if key else ""
        out.append(f"| {f['family']} | `{f['file']}` (weight {f['weight']}) | `read` the file with `project/` in front | {css} | `{f['family'].lower()}` |")
    for k in order:
        if k not in d:
            continue
        fam = d[k]
        toks = fam["tokens"]
        out += ["", f"## {title(k)}", ""]
        if fam.get("note"):
            out += [fam["note"], ""]
        use = f"padding: var(--{toks[0]['name']});" if k == "spacing" else f"/* var(--{toks[0]['name']}) */"
        out += ["### Use", "", "```css", use, "```", "", f"### Tokens ({len(toks)})", "", "| token | value | usage |", "| --- | --- | --- |"]
        for t in toks:
            v = t["value"]
            if isinstance(v, dict):
                vals = per_theme(t, themes)
                v = vals[first] + "".join(f" · {th}: {vals[th]}" for th in themes[1:] if vals[th] != vals[first])
            out.append(f"| `{t['name']}` | {v} | {t.get('usage', '')} |")
    return "\n".join(out) + "\n"


def main():
    d = json.loads((ROOT / "tokens.json").read_text())
    (ROOT / "tokens.css").write_text(compile_css(d))
    (ROOT / "api").mkdir(exist_ok=True)
    (ROOT / "api" / "tokens.md").write_text(compile_md(d))
    print("tokens.css and api/tokens.md written")


if __name__ == "__main__":
    main()
